version = 3.7.17
runner.dialect = scala3
maxColumn = 100
align.preset = more
rewrite.rules = [SortImports, RedundantBraces, RedundantParens]
spaces.inImportCurlyBraces = true
docstrings.style = Asterisk
newlines.afterCurlyLambdaParams = squash
